### ISSUE TITLE
TypeError: undefined is not a function 

### ISSUE THREAD

**Issue by whdigger** [postcss/postcss-simple-vars#16]
I create mixins it 's work if not use postcssSimplevars, which him don't work
```
gulp.task('tp', function () {
// dependencies
    var fs = require("fs");

// css to be processed
    var css = fs.readFileSync("src/postcss/front/form/calc.pcss", "utf8");

// process css
    var output = corepostcss()
        .use(postcssImport({from: 'src/postcss/front/**/*.pcss'}))
        .use(postcssMixins({mixinsDir: configLocal.currentsrcPath + '/' + configData.src.mixinsDir}))
    .use(postcssSimplevars)
        .process(css)
        .css;

    console.log(output);
});

```
mixins file
```
var fs = require('fs');

module.exports = function (mixin, side) {

    var path = __dirname + '/../data/' + side + '.json';
    var options = {};
    if (fs.existsSync(path)) {
        try {
            options = require(path);
        } catch (ex) {
            console.log('Ошибка чтения файла ' + 'data/' + side + '.json');
            return null;
        }
    }

    var yPart = options.yPart || 23;
    var startWidth = options.startWidth || 43;
    var offsetWidth = options.offsetWidth || 7;
    var mapSectionHeight = options.mapSectionHeight || 25;

    var whiteList = ['left', 'right'];

    if (whiteList.indexOf(side) === -1)  return;

    var propElement = function (i) {

        var shiftIter = iter - i + 1;
        //var extraShift = (i == 1? 0 : 2);
        var extraShift = 10;

        var bgPosY = +mapSectionHeight * shiftIter + +yPart;
        var bgPosX = 0;

        var topPos = +mapSectionHeight * i + +yPart;
        var element = {
            top: topPos + 'px',
            width: (startWidth + offsetWidth * shiftIter) - i + extraShift + 'px'
        };

        if (side == 'right') {
            bgPosX = 941 - bgPosY;
            bgPosY = topPos;
            element.right = 0;
        }

        element['background-position'] = bgPosX + 'px ' + bgPosY + 'px';
        return element;
    };

    var iter = 11;

    var nameSelector = '&.' + side + '-part';
    var arrayJson = [];

    for (var i = 1; i < iter; i++) {
        arrayJson.push('"' + nameSelector + i + '":' + JSON.stringify(propElement(i)));
    }

    return JSON.parse('{' + arrayJson.join(',') + '}');
};
```

postcss.file
```
@mixin map right;
```
Error log
```
/node_modules/gulp/node_modules/orchestrator/index.js:153
			throw err;
			      ^
TypeError: undefined is not a function
    at /node_modules/postcss-simple-vars/index.js:71:40
    at /node_modules/postcss-mixins/node_modules/postcss/lib/container.js:104:26
    at Rule.each (/node_modules/postcss-mixins/node_modules/postcss/lib/container.js:91:22)
    at Rule.eachInside (/node_modules/postcss-mixins/node_modules/postcss/lib/container.js:103:21)
    at /node_modules/postcss/lib/container.js:107:32
    at Root.each (/node_modules/postcss/lib/container.js:91:22)
    at Root.eachInside (/node_modules/postcss/lib/container.js:103:21)
    at /node_modules/postcss-simple-vars/index.js:66:13
    at module.exports.postcss (/node_modules/postcss-simple-vars/index.js:91:21)
    at LazyResult.run (/node_modules/postcss/lib/lazy-result.js:162:24)
```

**Comment by whdigger** [comment]
Error in block, but why?
```
if (side == 'right') {
      bgPosX = 941 - bgPosY;
      bgPosY = topPos;
      element.right = 0;
}
```

**Comment by whdigger** [comment]
Change element.right = 0 on element['right'] = 0 + 'px' and work ;)

**Comment by whdigger** [comment]
0 no support for css

**Comment by ai** [comment]
@whdigger do you use latest version of `postcss-simple-var` and `postcss-mixins`?

* In latest version of `postcss-simple-vars` there is no function call in 71 line.
* Latest version of `postcss-simple-vars` has fix for numbers in `decl.value`.
* Latest version of `postcss-mixins` automatically converts numbers from obj mixins to string.
