### ISSUE TITLE
Camelcase variable names do not work

### ISSUE THREAD

**Issue by presidenten** [postcss/postcss-simple-vars#64]
Using camelcase variable names causes an error in webpack and does not compile correctly.

Testcase:
```javascript
postcss([
    require('postcss-less-vars')({
        variables: {
            bgColor: 'red',
            bgcolor: 'red'
        }
    })
])
```

This works: 
```css
div {
  background-color: @bgcolor;
}
```

This does not work:
```css
div {
  background: @bgColor;
}
```

and throws an error like this:
```shell
ERROR in ./~/css-loader?sourceMap!./~/vue-loader/lib/style-rewriter.js?...
Module build failed: RangeError: Maximum call stack size exceeded
    at RegExp.exec (native)
    at RegExp.[Symbol.match] (native)
    at String.match (native)
    at Vars.replace (mypath/node_modules/postcss-less-vars/index.js:57:26)
    at Vars.<anonymous> (mypath/node_modules/postcss-less-vars/index.js:68:26)
    at Array.forEach (native)
    at Vars.replace (mypath/node_modules/postcss-less-vars/index.js:60:18)
    at Vars.<anonymous> (mypath/node_modules/postcss-less-vars/index.js:68:26)
    at Array.forEach (native)
    at Vars.replace (mypath/node_modules/postcss-less-vars/index.js:60:18)
    at Vars.<anonymous> (mypath/node_modules/postcss-less-vars/index.js:68:26)
    at Array.forEach (native)
    at Vars.replace (mypath/node_modules/postcss-less-vars/index.js:60:18)
    at Vars.<anonymous> (mypath/node_modules/postcss-less-vars/index.js:68:26)
    at Array.forEach (native)
    at Vars.replace (mypath/node_modules/postcss-less-vars/index.js:60:18)
```

**Comment by presidenten** [comment]
Sorry, in wrong project
